# export_env.cmake Always writes global /tmp/build-meta files for automation

string(ASCII 27 Esc) # escape character

set(RESET   "${Esc}[0m")
set(BOLD    "${Esc}[1m")
set(GREEN   "${Esc}[32m")
set(YELLOW  "${Esc}[33m")
set(CYAN    "${Esc}[36m")


# --- Variables to export (always the same) ---
set(EXPORT_VARS 
   PROJECT_NAME
   CMAKE_SOURCE_DIR
   CMAKE_BINARY_DIR
)

# --- Ensure tmp folder exists ---
set(EXPORT_DIR "/tmp/build-meta")
file(MAKE_DIRECTORY ${EXPORT_DIR})

# --- File paths ---
set(ENV_FILE "${EXPORT_DIR}/env.sh")

# --- Write env.sh ---
file(WRITE ${ENV_FILE} "# Autogenerated by export_env.cmake\n")
foreach(_var ${EXPORT_VARS})
  file(APPEND ${ENV_FILE} "export ${_var}=\"${${_var}}\"\n")
endforeach()

# --- Output info ---
message(
  STATUS
    "${GREEN}[XENV]:${RESET} wrote ${CYAN}${ENV_FILE}${RESET}"
)

foreach(_var ${EXPORT_VARS})
  message(STATUS "  ${YELLOW}${_var}${RESET} = ${BOLD}${${_var}}${RESET}")
endforeach()
